### PR TITLE
feat: disable caching for v1.secrets, avoid listing secrets cluster wide

### PR DESCRIPTION
**Pull request by jolbax**
This operator needs to access a specific secret in order to be able to communicate with the external providers. 
In the way that it is configured by now, it is caching all (cluster wide) secret objects, therefore it needs "list" and "watch" role permissions. 
This is a security issue, if you consider that a "list" operation sends all "secret" objects with all confidential information in it. Sure the operator code is written in a way that only "get" operations are performed, never the less the ServiceAccount has too much (unneeded) permissions. In case that a service account token gets compromised, the invader would be able to get all cluster-secrets. 

Disabling the caching of v1.Secrets reduces the risk following the principal of least privilege 

This code was throughly tested with the Azure provider

### CODE REVIEW

**Comment by jolbax** [comment]
Hi @sabre1041, do you know why are all those checks failing? I just realised that it is not only for my PR.
Best,

**Comment by jolbax** [comment]
Does somebody knows how can I make this change real? Any ideas?

**Comment by sabre1041** [comment]
@jolbax Hi there. Been looking at dependencies and have opened #229 . When that is integrated, if you could rebase off of it, I'll be happy to review the PR.

Apologies for the delay

**Comment by jolbax** [comment]
Hi @sabre1041, 
Thanks for the feedback and apologies for the delay as well.
Now is everything setup as wished

**Comment by jolbax** [comment]
Hi, any news on this?

**Comment by jolbax** [comment]
still waiting... ☹️

**Comment by sabre1041** [comment]
@jolbax I have not had a chance to verify this, but have you tested this PR with secrets located in a separate namespace to where the operator is deployed? this was a feature that was added several months ago to support leveraging credentials that may have been created for other purposes, such as cluster authentication

**Comment by jolbax** [comment]
@sabre1041 Yes, this is exactly our use-case. 
As you can see [here](https://github.com/redhat-cop/group-sync-operator/pull/217/files#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261R91) the only thing that changes is that the "managers client" should not cache information of the Kind "v1.Secret". Disabling this, makes the "List" verb for "v1.Secret" unnecessary. And this is what we want to achieve. But the "managers client" is still free to access specific secrets cluster wide.

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
