### PR TITLE
Drop username&password option

### LINKED ISSUE #113: github: drop username/password option
AFAIK GH has stopped accepting username/password for API-calls: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/

### PR DESCRIPTION
**Pull request by davidkarlsen**
Fixes #113

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@sabre1041 WDYT?

**Comment by davidkarlsen** [comment]
@raffaelespazzoli ptal?

**Review by sabre1041 — APPROVED** [review]
LGTM

**Comment by sabre1041** [comment]
@davidkarlsen Thanks for this. Good timing too

https://thenewstack.io/github-kisses-passwords-goodbye/

**Pull request merged**
